# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[social]]
    identifier="wechat"
    name      ="微信"
    url       ="/wechat/1734600678477.jpg"
    weight    =1
    [social.params]
        icon="brand-wechat"

[[social]]
    identifier="github"
    name      ="GitHub"
    url       ="https://github.com/game1991"
    weight    =2
    [social.params]
        icon="brand-github"

[[social]]
    identifier="mail"
    name      ="Email"
    url       ="mailto:game199le@gmail.com"
    weight    =3
    [social.params]
        icon="brand-gmail"

[[social]]
    identifier="twitter"
    name      ="Twitter"
    url       ="https://twitter.com"
    weight    =4
    [social.params]
        icon="brand-twitter"
